//! exception_1
// console.log(1);
// try {
//   console.log(2);
//   if (e) {
//     throw "some error";
//   }
//   console.log(3);
// } catch (error) {
//   console.log(4);
// }
// console.log(5);

//! exception_2
// Finlay

//!3 exception_3

// function safeDiv(num1, num2) {
//   if (num2 == 0) {
//     throw "Denominator is zero";
//   }
//   let result = num1 / num2;
//   console.log(result);
//   return result;
// }
// safeDiv(10, 0);
